### PR TITLE
Tuples

### PR DESCRIPTION
**Pull request by Fayruz-P**

### CODE REVIEW

**Review by Sahur-Maharaj — APPROVED** [review]
All looking good ->code correct and ready to merge.

**Comment by lehlohonolotladi** [comment]
Happiness!

**Comment by lehlohonolotladi** [comment]
Great!

**Review by lehlohonolotladi — APPROVED** [review]

**Review by SeabelaSHEDO — APPROVED** [review]
cool

**Review by SeabelaSHEDO — APPROVED** [review]

**Comment by SeabelaSHEDO** [comment]
Perfect

**Comment by lehlohonolotladi** [comment]
Great!

**Comment by lehlohonolotladi** [comment]
Great

**Pull request merged**
