### PR TITLE
Added Section_14(dictionaries) files

### PR DESCRIPTION
**Pull request by Fayruz-P**

### CODE REVIEW

**Review by Sahur-Maharaj — APPROVED** [review]
All code good branch can be merged.

**Review by lehlohonolotladi — APPROVED** [review]
Happiness

**Review by SeabelaSHEDO — APPROVED** [review]
cool

**Comment by nkcubeko12** [comment]
Cool

**Review by nkcubeko12 — COMMENTED** [review]
Good

**Review by nkcubeko12 — COMMENTED** [review]
Good

**Pull request merged**
