### PR TITLE
Added Section_25(built_in_modules) files

### PR DESCRIPTION
**Pull request by Fayruz-P**

### CODE REVIEW

**Review by lehlohonolotladi — COMMENTED** [review]
Happiness!

**Review by Sahur-Maharaj — APPROVED** [review]
Code all good

**Review by Vincentmt58 — APPROVED** [review]
nice

**Review by nkcubeko12 — APPROVED** [review]
Good!

**Review by SeabelaSHEDO — APPROVED** [review]
cool

**Pull request merged**
